export const jobPosts = [
  {
    title: "Recruiter",
    url: "/jobseekers/job/Recruiter-1433617",
    posterName: "Sheena Grace Coquilla",
    postedDate: "Jul 29, 2025",
    salary: "$250/month",
    description:
      "I'm looking for someone who has used LinkedIn before to create jobs and manage applicants for our company.",
    tags: [""],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.079Z",
  },
  {
    title: "Paid Ads & Digital Marketing Expert (Google, Meta, LinkedIn)",
    url: "/jobseekers/job/Paid-Ads-Digital-Marketing-Expert-Google-Meta-LinkedIn-1433615",
    posterName: "Ben Field",
    postedDate: "Jul 29, 2025",
    salary: "P400 – P600/hr per hour",
    description:
      "We’re hiring a performance-driven digital marketer. You’ll own paid ads, Google Business, Meta Business Suite setup, and lead generation. We want someone who’s highly experienced, data-focused, and ready to deliver results fast. Requirements: Proven track record managing high-performing Google, Meta,…",
    tags: ["Google Ads", "Facebook Ads", "Meta Business Suite"],
    employmentType: "Part Time",
    createdAt: "2025-07-29T06:09:25.080Z",
  },
  {
    title: "Ads Expert - Meta, Google and LinkedIn",
    url: "/jobseekers/job/Ads-Expert-Meta-Google-and-LinkedIn-1433614",
    posterName: "Joshua Smibert",
    postedDate: "Jul 29, 2025",
    salary: "Share your starting rate ($ USD/Hour)",
    description:
      "Summary: We're looking for someone who: 1. Has hands-on experience managing paid ads on LinkedIn, Meta (Facebook/Instagram), and Google Ads 2. Knows how to run B2B campaigns that actually convert 3. Thinks strategically — someone who understands how audience, message,…",
    tags: ["Google Ads", "Facebook Ads", "LinkedIn Marketing"],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.081Z",
  },
  {
    title: "Video Editor",
    url: "/jobseekers/job/Video-Editor-1428146",
    posterName: "Bright Agency",
    postedDate: "Jul 29, 2025",
    salary: "$1000 to $1400 USD/month",
    description:
      "Turn Your Creativity Into a Career! We’re hiring a full-time content creator and short-form video editor to help build the next generation of viral digital personas. If you're obsessed with TikTok, Reels, and making content that actually gets attention, this…",
    tags: [
      "Video Content Creation",
      "Video Editing",
      "Social Media Video Editing",
    ],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.081Z",
  },
  {
    title:
      "Experienced Video Editor (META, TIKTOK ADS) – Ad Remixer & Optimizer",
    url: "/jobseekers/job/Experienced-Video-Editor-META-TIKTOK-ADS-Ad-Remixer-Optimizer-1433612",
    posterName: "D",
    postedDate: "Jul 29, 2025",
    salary: "TBC On Experience",
    description:
      "The Role: We’re expanding and looking for a 2nd highly skilled Video Editor who can turn raw UGC and creator clips into scroll-stopping, sales-generating, retention-optimized ad creatives. You’ll be working directly with our influencer outreach manager and media buyer to…",
    tags: ["Video Content Creation", "Video Editing", "CapCut"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.082Z",
  },
  {
    title: "Email Marketing Designer",
    url: "/jobseekers/job/Email-Marketing-Designer-1433611",
    posterName: "Romeo Barr",
    postedDate: "Jul 29, 2025",
    salary: "1000",
    description:
      "Need a email designer good pay whatsap me +44 7950 353595 EXPEREICNED ONLY you'll be working with some amazing brands if we choose you. Please whatsapp ASAP start",
    tags: ["Email Marketing", "Design", "Klaviyo"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.082Z",
  },
  {
    title:
      "Marketing and Ads Specialist (Full-Time, Onsite – Project 8, Quezon City)",
    url: "/jobseekers/job/Marketing-and-Ads-Specialist-Full-Time-Onsite-Project-8-Quezon-City-1424858",
    posterName: "Roadside Autofixer",
    postedDate: "Jul 29, 2025",
    salary: "TBD",
    description:
      "We’re looking for a sharp, creative, and results-driven Marketing and Ads Specialist to join our team in Project 8, Quezon City. This is a full-time, onsite position ideal for someone who knows how to turn clicks into conversions, especially through…",
    tags: ["Facebook marketing", "Facebook Ads", "Tiktok Ads"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.083Z",
  },
  {
    title: "AI Chatbot SaaS Developer – Travel & Tourism Industry",
    url: "/jobseekers/job/AI-Chatbot-SaaS-Developer-Travel-Tourism-Industry-1433609",
    posterName: "Peter Summers",
    postedDate: "Jul 29, 2025",
    salary: "Based on experience",
    description:
      "Are you passionate about AI, travel, and building cutting-edge SaaS products from the ground up? We're looking for a highly skilled and visionary developer to help bring our AI-powered chatbot platform for the travel and tourism industry to life. About…",
    tags: ["Web Programming"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.084Z",
  },
  {
    title: "Online Math Teacher(Near-Native Accent)",
    url: "/jobseekers/job/Online-Math-TeacherNear-Native-Accent-1357585",
    posterName: "sarah zhao",
    postedDate: "Jul 29, 2025",
    salary: "US$ 3-4",
    description:
      "About Pomelo Academy: Pomelo Academy is an innovative online international school dedicated to delivering high-quality education to students worldwide. We provide a dynamic and engaging learning environment, catering to individualized instruction that transcends geographical boundaries. Job Description: We are seeking…",
    tags: [""],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.087Z",
  },
  {
    title: "Online Math Teacher(Near-Native Accent)",
    url: "/jobseekers/job/Online-Math-TeacherNear-Native-Accent-1356567",
    posterName: "sarah zhao",
    postedDate: "Jul 29, 2025",
    salary: "US$ 3-4",
    description:
      "About Pomelo Academy: Pomelo Academy is an innovative online international school dedicated to delivering high-quality education to students worldwide. We provide a dynamic and engaging learning environment, catering to individualized instruction that transcends geographical boundaries. Job Description: We are seeking…",
    tags: [""],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.087Z",
  },
  {
    title: "Car Wrap Graphic Designer",
    url: "/jobseekers/job/Car-Wrap-Graphic-Designer-1433603",
    posterName: "Jessenia Alfaro",
    postedDate: "Jul 29, 2025",
    salary: "$200-$500 month",
    description:
      "Southern California | Business Hours Availability | Growth Opportunity A fast-growing vehicle wrap company in Southern California is looking for a Car Wrap Graphic Designer with a strong command of Adobe Illustrator and previous experience in designing and paneling wraps…",
    tags: ["Illustrator", "Graphic Design", "Teamwork"],
    employmentType: "Gig",
    createdAt: "2025-07-29T06:09:25.088Z",
  },
  {
    title: "VP of Sales (Build & Scale from Scratch)",
    url: "/jobseekers/job/VP-of-Sales-Build-Scale-from-Scratch-1433594",
    posterName: "Nebroo Recruitment",
    postedDate: "Jul 29, 2025",
    salary: "HIGH SALARY",
    description:
      "Please watch this Loom video for a detailed explanation of the role: www.loom.com/share/77f1cca87a82477aa57da283fe6b5205?live_rewind=1 DISCLAIMER: Who this is NOT for This is not a support role. If your experience is mostly in customer service or tech support, this won’t be a…",
    tags: [
      "Telemarketing",
      "Inbound Sales",
      "Call Center Operations Management",
    ],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.088Z",
  },
  {
    title: "Advertorial builder & copywriter",
    url: "/jobseekers/job/Advertorial-builder-copywriter-1433592",
    posterName: "Fredrik Alm",
    postedDate: "Jul 29, 2025",
    salary: "$520 per month (PHP 300000)",
    description:
      "We are a growing pain-relief brand who are now expanding. We are looking to onboard a full-time advertorial expert and copywriter. You should be able to both copy advertorials and make your own, on Funnelish. You should know about fundamentals…",
    tags: ["Copywriting", "Funnelish"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.089Z",
  },
  {
    title: "Director of Sales(TV Ads – Start Solo, Build Team)",
    url: "/jobseekers/job/Director-of-SalesTV-Ads-Start-Solo-Build-Team-1433591",
    posterName: "Nebroo Recruitment",
    postedDate: "Jul 29, 2025",
    salary: "HIGH SALARY",
    description:
      "Please watch this Loom video for a detailed explanation of the role: www.loom.com/share/77f1cca87a82477aa57da283fe6b5205?live_rewind=1 DISCLAIMER: Who this is NOT for This is not a support role. If your experience is mostly in customer service or tech support, this won’t be a…",
    tags: [
      "Telemarketing",
      "Inbound Sales",
      "Call Center Operations Management",
    ],
    employmentType: "Part Time",
    createdAt: "2025-07-29T06:09:25.089Z",
  },
  {
    title: "Inbound Sales Call Center Manager HIGH SALARY",
    url: "/jobseekers/job/Inbound-Sales-Call-Center-Manager-HIGH-SALARY-1433590",
    posterName: "Nebroo Recruitment",
    postedDate: "Jul 29, 2025",
    salary: "HIGH SALARY",
    description:
      "Please watch this Loom video for a detailed explanation of the role: www.loom.com/share/77f1cca87a82477aa57da283fe6b5205?live_rewind=1 DISCLAIMER: Who this is NOT for This is not a support role. If your experience is mostly in customer service or tech support, this won’t be a…",
    tags: [
      "Telemarketing",
      "Inbound Sales",
      "Call Center Operations Management",
    ],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.089Z",
  },
  {
    title: "Inbound Sales Call Center Manager (Build & Scale from Scratch)",
    url: "/jobseekers/job/Inbound-Sales-Call-Center-Manager-Build-Scale-from-Scratch-1433589",
    posterName: "Nebroo Recruitment",
    postedDate: "Jul 29, 2025",
    salary: "HIGH SALARY",
    description:
      "Please watch this Loom video for a detailed explanation of the role: www.loom.com/share/77f1cca87a82477aa57da283fe6b5205?live_rewind=1 DISCLAIMER: Who this is NOT for This is not a support role. If your experience is mostly in customer service or tech support, this won’t be a…",
    tags: [
      "Telemarketing",
      "Inbound Sales",
      "Call Center Operations Management",
    ],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.090Z",
  },
  {
    title: "Creator Relationship Specialist",
    url: "/jobseekers/job/Creator-Relationship-Specialist-1433586",
    posterName: "Alexander Moy",
    postedDate: "Jul 29, 2025",
    salary: "Starting pay is $1/hour USD",
    description:
      "We’re hiring a Creator Relationship Specialist to support our team with messaging, tracking activity, and helping creators stay on top of their social media goals. This is an entry-level position with opportunities for growth — many of our VAs now…",
    tags: ["Influencer Marketing", "Chat Support", "Virtual Assistant"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.090Z",
  },
  {
    title: "Corporate Headshot Photo Editor (Adobe Lightroom & Photoshop)",
    url: "/jobseekers/job/Corporate-Headshot-Photo-Editor-Adobe-Lightroom-Photoshop-1433576",
    posterName: "Jeremy Bengtson",
    postedDate: "Jul 29, 2025",
    salary: "$160",
    description:
      "About the Role I’m looking for a photo editor who can review batches of corporate headshots, pick out the sharpest, in-focus images, and deliver ten polished final files per assignment. This is a task-based position with the potential for ongoing…",
    tags: ["Photo Editing", "Photoshop", "Photo Editing"],
    employmentType: "Gig",
    createdAt: "2025-07-29T06:09:25.090Z",
  },
  {
    title: "Legal; US Attorney",
    url: "/jobseekers/job/Legal-US-Attorney-1218080",
    posterName: "Melody",
    postedDate: "Jul 29, 2025",
    salary: "TBD",
    description:
      "We are seeking an Attorney who is licensed to practice law in both the Philippines and the United States, with a strong preference for those licensed in California, Florida, and Nevada (other states may be considered). This is a remote…",
    tags: ["Legal Services"],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.091Z",
  },
  {
    title: "Print-On-Demand (POD) Designer Manager",
    url: "/jobseekers/job/Print-On-Demand-POD-Designer-Manager-1433555",
    posterName: "HR",
    postedDate: "Jul 29, 2025",
    salary: "TBD",
    description:
      "Print-On-Demand (POD) Designer Manager We are looking for an experienced Print-On-Demand Designer Manager to lead our design team and oversee daily operations related to POD order fulfillment. This is a full-time, management-level role, perfect for someone who excels in Adobe…",
    tags: ["Photoshop", "Illustrator", "Print Design"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.091Z",
  },
  {
    title: "Content Operator (B2B & eCommerce Focus)",
    url: "/jobseekers/job/Content-Operator-B2B-eCommerce-Focus-1433550",
    posterName: "dropshipchinapro",
    postedDate: "Jul 29, 2025",
    salary: "$800 USD",
    description:
      "Location: Remote Job Overview: We are seeking a skilled Content Operator to join our team, specializing in business-to-business (B2B) content creation. This role will focus on producing high-quality, knowledge-driven articles and content that enhance our brand image and contribute to…",
    tags: [""],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.092Z",
  },
  {
    title: "REMOTE FLUTTER- IOS DEVELOPER",
    url: "/jobseekers/job/REMOTE-FLUTTER-IOS-DEVELOPER-1425679",
    posterName: "Chas",
    postedDate: "Jul 29, 2025",
    salary: "200 USD a week",
    description:
      "FLUTTER/IOS DEVELOPER - OMELAS AI (omelasai.com) Cutting-Edge AI-Powered Software Development - Remote Are you a top-tier graduate who excels at everything you touch? Omelas AI is revolutionizing software development by leveraging the latest AI tools to build bespoke applications at…",
    tags: ["Dart", "Flutter", "iOS Development"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.092Z",
  },
  {
    title: "N8N Automation Developer",
    url: "/jobseekers/job/N8N-Automation-Developer-1416235",
    posterName: "Sofia Toro",
    postedDate: "Jul 28, 2025",
    salary: "$4 - $6 USD hour",
    description:
      "Job Overview: Speedrack West — a fast-growing material handling company — is looking for a smart, reliable, and proactive N8N Developer to help automate key sales, marketing, and operations workflows. This is a part-time, remote role ideal for someone who…",
    tags: [""],
    employmentType: "Part Time",
    createdAt: "2025-07-29T06:09:25.093Z",
  },
  {
    title: "Futures Trader – Propfirm / NinjaTrader / Rithmic knowledge",
    url: "/jobseekers/job/Futures-Trader-Propfirm-NinjaTrader-Rithmic-knowledge-1399839",
    posterName: "A",
    postedDate: "Jul 28, 2025",
    salary: "P7-10k",
    description:
      "**Job Title: Futures Day Trader – NASDAQ or Gold** **Organization: Faith-Based Charitable Foundation** **Location: Remote, Philippines only** **Compensation: PHP 7000 to 10000 per month via PayPal** **Schedule: Full-time, Monday to Friday, US market hours (night shift PH time)** About Us…",
    tags: ["Forex Trading", "Technical Analysis", "Risk Management"],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.093Z",
  },
  {
    title:
      "Day Trader (Futures only NinjaTrader/Rithmic Expert) (similar to forex) Propfirm knowledge            Full Time",
    url: "/jobseekers/job/Full-Time-Day-Trader-Futures-only-NinjaTraderRithmic-Expert-similar-to-forex-Propfirm-knowledge-1395801",
    posterName: "A",
    postedDate: "Jul 28, 2025",
    salary: "P7-10k",
    description:
      "**Job Title: Day Trader – NASDAQ Futures or Gold** **Organization: Faith-Based Charitable Foundation** **Location: Remote, Philippines only** **Compensation: PHP 7000 to 10000 per month, based on consistency and strategy** **Schedule: Full-time, Monday to Friday, US market hours (night shift PH…",
    tags: ["Forex Trading", "Technical Analysis", "Risk Management"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.094Z",
  },
  {
    title: "Electrical Engineer for Power Distribution Centers",
    url: "/jobseekers/job/Electrical-Engineer-for-Power-Distribution-Centers-1129370",
    posterName: "Leaveil Skinner",
    postedDate: "Jul 29, 2025",
    salary: "$500",
    description:
      "As an Electrical Engineer specializing in Power Distribution Centers, you will be responsible for designing, analyzing, and optimizing electrical distribution systems within industrial and commercial settings. Your role will involve collaborating with cross-functional teams to ensure efficient power distribution, compliance…",
    tags: [""],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.094Z",
  },
  {
    title: "Mechanical Engineer for Power Distribution Centers",
    url: "/jobseekers/job/Mechanical-Engineer-for-Power-Distribution-Centers-1129371",
    posterName: "Leaveil Skinner",
    postedDate: "Jul 29, 2025",
    salary: "$500",
    description:
      "Overview: As a Mechanical Engineer specializing in Power Distribution Centers, you will play a crucial role in designing, analyzing, and optimizing the mechanical systems and components associated with power distribution infrastructure. Your expertise will ensure the efficient operation, reliability, and…",
    tags: [""],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.094Z",
  },
  {
    title: "Registered Structural Engineer",
    url: "/jobseekers/job/Registered-Structural-Engineer-1288734",
    posterName: "Leaveil Skinner",
    postedDate: "Jul 29, 2025",
    salary: "700 Monthly",
    description:
      "Job Summary We are seeking a talented and detail-oriented Structural Engineer to join our manufacturing team specializing in power distribution systems and modular homes. The successful candidate will play a pivotal role in the design, analysis, and optimization of structural…",
    tags: ["Structural Engineering", "Communication", "Leadership"],
    employmentType: "Any",
    createdAt: "2025-07-29T06:09:25.095Z",
  },
  {
    title: "Automation Expert (Zoho CRM) | System Builder + Integrator",
    url: "/jobseekers/job/Automation-Expert-Zoho-CRM-System-Builder-Integrator-1433475",
    posterName: "Monica T",
    postedDate: "Jul 29, 2025",
    salary: "$1,000 - $1,200 per month",
    description:
      "If you live and breathe Zoho CRM, love building workflows that actually work, and get hyped when everything flows automatically—this is your zone of genius. We’re looking for a full-time Automation Expert to join a fast-growing, heart-led coaching company based…",
    tags: ["Clickfunnels", "Robotic Process Automation"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.095Z",
  },
  {
    title: "Senior Automation Specialist",
    url: "/jobseekers/job/Senior-Automation-Specialist-1433474",
    posterName: "Motii",
    postedDate: "Jul 29, 2025",
    salary: "90,000 +",
    description:
      "Motii is looking for a Senior Automation Specialist to support and lead the successful delivery of automation-heavy CRM implementation projects. You’ll work closely with our clients and internal team to gather requirements, configure automations using tools like Zapier, Make, and…",
    tags: ["Pipedrive", "Zapier", "Make.com"],
    employmentType: "Full Time",
    createdAt: "2025-07-29T06:09:25.095Z",
  },
];
